spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: 127.0.0.1:29092
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: group_id
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
auto:
  create:
    topics:
      enable: 'true'
topic:
  name:
    producer: topic-test-1
    consumer: topic-test-1